allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2102.21'
  - '@angular-devkit/core@21.2.21'
  - '@angular-devkit/schematics@21.2.21'
  - '@angular/build@21.2.21'
  - '@angular/cli@21.2.21'
  - '@schematics/angular@21.2.21'
